import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "./components/Header";
import Footer from "./components/Footer";
import { Box } from '@mui/material';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Internship",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Box mt={8}>
          {children}
        </Box>
        <Box mt={8}>
        <Footer />
        </Box>
      </body>
    </html>
  );
}
